version : 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - [%(filename)s:%(lineno)d]'
    datefmt: '%Y-%m-%d %H:%M:%S'


filters:
  only_info:
    (): logs.OnlyInfoFilter

handlers:

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: log/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    filters: [only_info]

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: log/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8


loggers:
  webui:
    level: DEBUG
    handlers: [file, error_file]
    propagate: false

