version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "6060:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - sleep-network

  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:CHANGE_ME_PLS@db:5432/sleep_capsule
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sleep-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=sleep_capsule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHANGE_ME_PLS
      - PGUSER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sleep-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sleep_capsule"]
      interval: 5s
      timeout: 3s
      retries: 5
    expose:
      - "5432"

volumes:
  postgres_data:

networks:
  sleep-network:
    driver: bridge
